### ISSUE TITLE
Ensure zip file?

### ISSUE THREAD

**Issue by dobraczka** [cthoyt/pystow#26]
Hello,
I love the project. However I am missing something like an `ensure_zip_file` function. While ensuring that the actual `.zip` is there can be done with `ensure`, it would be nice to have a functionality, where I ensure a file from this zip is there, and load this file as fileobject, to then read it in however it is needed.
Poking around in the code I found `Module.ensure_open_zip`. I think this contextmanager can be easily wrapped for the API, to get what I need like this:

```python
def ensure_open_zip(
    key: str,
    *subkeys: str,
    url: str,
    inner_path: str,
    name: Optional[str] = None,
    download_kwargs: Optional[Mapping[str, Any]] = None,
):
    _module = Module.from_key(key, ensure_exists=True)
    return _module.ensure_open_zip(*subkeys, url=url, inner_path=inner_path, name=name)

```

If it's fine with you I could make a PR and add it (with tests and doc of course)?

**Comment by cthoyt** [comment]
Hi @dobraczka, I'm happy to accept a PR for more functionality. Please check in the module and the utils, since there are a few things I've added but never got around to documenting and exposing.

**Comment by cthoyt** [comment]
E.g. you might want to check out 

https://github.com/cthoyt/pystow/blob/c3d708c4fe3d16e750669c5130aa2d1f8bbc8e58/src/pystow/module.py#L320-L340

**Comment by dobraczka** [comment]
Yes, while writing the test I saw that I can easily do what I want with simply using:
```python
from pystow import module
with module("test").ensure_open_zip(url=url, inner_path=inner_path) as file:
     ...
```
So instead of the initial code snippet I would simply add this finding to the README.
