### ISSUE TITLE
Variants of ensure functions focused on loading

### ISSUE THREAD

**Issue by bgyori** [cthoyt/pystow#36]
Currently, pystow provides a number of `ensure_*` functions that target different file types, downloads them if not available, and loads them. For instance, `ensure_csv` takes a path to a CSV file and loads it with pandas. However, all of these functions also require a `url` argument from which the file is first downloaded if it doesn't already exist. I think it would be useful to have variants of these functions where the same functionality of loading canonical file types is provided but without the url/download part, under the assumption that the given file is already there and never necessarily came from a URL in the first place. I would definitely use pickle loading or JSON loading for instance, knowing that a given file is already there.

**Comment by cthoyt** [comment]
Great suggestion! Several of the functions you might want to use are already available through pystow.utils. I’ll try to improve the docs to make this a bit more obvious. 

Was the a specific one you wanted to use?

**Comment by bgyori** [comment]
I suppose it would be equally useful to have a corresponding variant for all the `ensure_*` functions (the ones that specify a specific file format) but personally I'd probably use json and pickle (this doesn't exist yet) most often.

**Comment by cthoyt** [comment]
Okay on a second read I think I understood what you were asking for and made a demo in #37 that just address CSV, pickle, and JSON opening. This doesn't affect any existing functionality so I'll make a release to PyPI so you can try it out.

The archetype is pretty general and could be pretty easily extended to other `ensure_*` functions to implement corresponding `open_*` functions.
