### ISSUE TITLE
Package on Anaconda via conda-forge?

### ISSUE THREAD

**Issue by sgbaird** [cthoyt/pystow#49]
https://conda-forge.org/docs/maintainer/adding_pkgs.html

https://github.com/sparks-baird/matbench-genmetrics/pull/47#discussion_r939048551

**Comment by cthoyt** [comment]
if i can figure this out, sure. I'm traveling tomorrow and will try to get it set up then

**Comment by sgbaird** [comment]
@cthoyt thanks for being willing to take a look!

**Comment by sgbaird** [comment]
@cthoyt I'm still waiting on the `conda-forge` devs to merge mine https://github.com/conda-forge/staged-recipes/pull/19864, but I will let you know if I run into any issues with incorporating it. In the meantime, I did a local installation in a fresh conda env and was able to run a few examples from the README and nothing seems incompatible based on the `meta.yaml` recipe you uploaded, so I don't think it will pose a problem. I'll keep the reproducibility issue in mind. One of the recommendations from [PyScaffold's data science extension](https://github.com/pyscaffold/pyscaffoldext-dsproject) template is:

> ## Dependency Management & Reproducibility
> 
> 1. Always keep your abstract (unpinned) dependencies updated in `environment.yml` and eventually
>    in `setup.cfg` if you want to ship and install your package via `pip` later on.
> 2. Create concrete dependencies as `environment.lock.yml` for the exact reproduction of your
>    environment with:
>    ```bash
>    conda env export -n matbench-genmetrics -f environment.lock.yml
>    ```
>    For multi-OS development, consider using `--no-builds` during the export.
> 3. Update your current environment with respect to a new `environment.lock.yml` using:
>    ```bash
>    conda env update -f environment.lock.yml --prune
>    ```

I also came across https://github.com/conda-incubator/conda-lock. Do either of these address that issue? I'm sure each comes with its slew of issues.

**Comment by cthoyt** [comment]
pystow only relies on a small number of super popular packages so i'm not super worried about pinning their versions. Also, this sounds like it's catering to end-users who aren't really creating reusable software

**Comment by cthoyt** [comment]
I'm going to close this as pystow is now on conda-forge. I'm not exactly sure what the update instructions are so i will burn that bridge when we need to come to it
