### ISSUE TITLE
Feature: Add progress bar during download

### ISSUE THREAD

**Issue by glass-ships** [cthoyt/pystow#60]
Optionally behind a `verbose` parameter, but it'd be nice in some cases for the user to be aware that downloads are happening in the background.

**Comment by sgbaird** [comment]
@glass-ships agreed, a progress bar would be very nice for large downloads (e.g., multiple GBs)

@cthoyt

**Comment by sgbaird** [comment]
Related: https://stackoverflow.com/a/21868231/13697228
