### ISSUE TITLE
Missing type information

### ISSUE THREAD

**Issue by dobraczka** [cthoyt/pystow#67]
I just noticed, that the type information of pystow is not shipped, because no `py.typed` file is present. See this mypy output I had in another project.
```
...
sylloge/base.py:28: error: Skipping analyzing "pystow": module is installed, but missing library stubs or py.typed marker  [import-untyped]
sylloge/base.py:30: error: Skipping analyzing "pystow.utils": module is installed, but missing library stubs or py.typed marker  [import-untyped]
....
```
This can be easily fixed, [by adding a `py.typed` file](https://dev.to/whtsky/don-t-forget-py-typed-for-your-typed-python-package-2aa3) inside `src/pystow`.

**Comment by cthoyt** [comment]
@dobraczka new release v0.5.3 on PyPI and here https://github.com/cthoyt/pystow/releases/tag/v0.5.3
